language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
    - stable
    - nightly
matrix:
    allow_failures:
        - rust: nightly
before_script:
    - rustup component add rustfmt
    - rustup component add clippy
script:
    - cargo check --all
    - cargo test --all --no-fail-fast
    - cargo fmt --all -- --check
    - cargo clippy -- -D warnings
